let APP_SITE = "https://igo.rs"
let APP_EMAIL = "clmn@igo.rs"
let APP_GROUP = "ac.obl.clmn.Clmn"
let APP_NAME = "Clmn"
let APP_TITLE = "Clmn: Tasks & Columns"
let APP_COPYRIGHT = "© 2022 igo.rs"
let APP_DESCRIPTION = "Tasks ❤️Columns"
